// <auto-generated />
using System;
using LoyloyShop.DbContexst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyloyShop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221004041712_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoyloyShop.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DateSell")
                        .HasColumnType("DateTime")
                        .HasColumnName("DateSell");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("EngineNumber");

                    b.Property<string>("FrameNumber")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("FrameNumber");

                    b.Property<int?>("MadeYear")
                        .HasMaxLength(50)
                        .HasColumnType("Integer")
                        .HasColumnName("MadeYear");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Name");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("PlateNumber");

                    b.Property<string>("Power")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Power");

                    b.Property<decimal>("PriceBuy")
                        .HasMaxLength(50)
                        .HasColumnType("Decimal")
                        .HasColumnName("PriceBuy");

                    b.Property<decimal?>("PriceSell")
                        .HasMaxLength(50)
                        .HasColumnType("Decimal(38,17)")
                        .HasColumnName("PriceSell");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("Integer")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
